### ISSUE TITLE
variable type fix

### ISSUE THREAD

**Issue by ruslanx3m** [deseven/pb-httprequest-manager#1]
Bug detected, variable type for "**concurrentRequests**" and "**concurrentRequests**" both are boolian ... need fix . .. to .l or .i .
![Screenshot 2022-04-20 191743](https://user-images.githubusercontent.com/24808164/164277616-ead2ac2c-44f9-4e1c-80f3-df6992e58ef9.png)
.

**Comment by deseven** [comment]
There's no boolean in PB, `.b` means byte, see "Variables and Types" section of the documentation.

**Comment by ruslanx3m** [comment]
I say, if you put 1000 concurrent request .. your code not work, byte only  -128 to +127 ...

**Comment by deseven** [comment]
I guess I can up it to 65535 (hard limit for unique connections per IP), but I doubt someone will ever need it. Browsers have 10 to 15 concurrent connections limit.

**Comment by ruslanx3m** [comment]
I develop a tool for quick testing server with neutral backend .. lightweight, I need maximum requests posible...and  timeout not work on server not respond..

**Comment by ruslanx3m** [comment]
I use nodejs ...

**Comment by deseven** [comment]
Oh, in that case you shouldn't even use my module or PB internal HTTP routines that use libcurl. Instead, I suggest using the [Network library](https://www.purebasic.com/documentation/network/index.html) and make connections manually. It will be MUCH faster that way, you'll be able to create more requests in the same timeframe and cut corners here and there to save even more time. You will still be limited to 65535 active connections (that's a TCP limitation, now way to go around that), but you will be able to close them much faster.

**Comment by ruslanx3m** [comment]
Hi, You was right, Network library is better for my needs .. how is better to do concurrent request ? using threads or like you do in your lib?  thx.

**Comment by deseven** [comment]
I would've tried creating an isolated thread-safe procedure which will spawn some number of connections and handle them, then it's a question of finding a balance between the number of connections per thread and the number of threads.

**Comment by ruslanx3m** [comment]
I wrote a code in pb, can I send you, may be you suggest a better way , changes ? to telegram ?

**Comment by deseven** [comment]
It will be better if you post it to PB forums, there are many more proficient people, especially in regards to network stuff.

**Comment by ruslanx3m** [comment]
ok. thanks.
